import { library } from '@fortawesome/fontawesome-svg-core'; 
import { 
    faMagnifyingGlass,
    faMicrochip,
    faMobile,
    faGear,
    faFloppyDisk,
    faLaptop,
    faTablet,
    faComputer,
    faHeadphones,
    faRotateRight,
    faHouse,
    faSimCard,
    faTag,
    faAppleWhole,
    faFile,
    faCircleUser,
    faCartShopping,
    faCircleCheck,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faMagnifyingGlass,
    faMicrochip,
    faMobile,
    faGear,
    faFloppyDisk,
    faLaptop,
    faTablet,
    faComputer,
    faHeadphones,
    faRotateRight,
    faHouse,
    faSimCard,
    faTag,
    faAppleWhole,
    faFile,
    faCircleUser,
    faCartShopping,
    faCircleCheck,
)